package Shapes.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Canvas_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Circle_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Color_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new ColorReference_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Point_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Polygon_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Rectangle_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Square_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        if (true) {
          if ("Shapes.editor.ShapeColor".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new ShapeColor());
          }
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }

  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ColorReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db15492eb2fL), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db15492eb16L), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db154960c83L), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db154974078L), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0xdb2f68134547bbdL), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0xdb2f681345485b1L), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0xdb2f6813442c6e9L), MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db15492eb20L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db15492eb15L)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7143c4151117487cL, 0xb5cff1a234b7a31dL, 0x60782db154974078L)).seal();
}
